version: 2

repo:
  public: java-server-sdk-consul

branches:
  - name: master
    description: 3.x - for Java SDK 5.0+
  - name: 1.x
    description: for Java SDK 4.x

publications:
  - url: https://oss.sonatype.org/content/groups/public/com/launchdarkly/launchdarkly-java-server-sdk-consul-store/
    description: Sonatype
  - url: https://javadoc.io/doc/com.launchdarkly/launchdarkly-java-server-sdk-consul-store
    description: documentation (javadoc.io)

jobs:
  - docker:
      image: gradle:7.3.3-jdk8
    template:
      name: gradle
      skip:
        - test  # Running the unit tests would require installing Consul. They've already been run in CI.

documentation:
  gitHubPages: true
