name: Build and Test

on:
  push:
    branches: [main, feat/**]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, feat/**]
    paths-ignore:
      - '**.md'

jobs:
  build-test-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        javaversion: [8, 11, 17, 19]
    runs-on: ${{ matrix.os }}
    services:
      consul:
        image: hashicorp/consul
        ports:
          - 8500:8500
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          java_version: ${{ matrix.javaversion }}

  build-test-windows:
    strategy:
      matrix:
        os: [windows-latest]
        javaversion: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Consul
        run: |
          $ProgressPreference = "SilentlyContinue"
          iwr -outf consul.zip https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_windows_amd64.zip
          mkdir consul
          Expand-Archive -Path consul.zip -DestinationPath consul
          cd consul
          sc.exe create "Consul" binPath="$(Get-Location)/consul.exe agent -dev"
          sc.exe start "Consul"

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          java_version: ${{ matrix.javaversion }}
